ExternalProject_Add(nghttp2
    GIT_REPOSITORY https://github.com/nghttp2/nghttp2.git
    SOURCE_DIR ${SOURCE_LOCATION}
    GIT_CLONE_FLAGS "--filter=tree:0"
    GIT_SUBMODULES ""
    UPDATE_COMMAND ""
    CONFIGURE_COMMAND ${EXEC} CONF=1 cmake -B <BINARY_DIR> -S <SOURCE_DIR>
        -G Ninja
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
        -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX}
        -DCMAKE_DISABLE_FIND_PACKAGE_OpenSSL=ON
        -DBUILD_SHARED_LIBS=OFF
        -DBUILD_STATIC_LIBS=ON
        -DBUILD_TESTING=OFF
        -DENABLE_DOC=OFF
        -DENABLE_FAILMALLOC=OFF
        -DENABLE_HTTP3=OFF
        -DENABLE_LIB_ONLY=ON
        -DWITH_JEMALLOC=OFF
        -DWITH_LIBBPF=OFF
        -DWITH_LIBXML2=OFF
        -DWITH_MRUBY=OFF
        -DWITH_NEVERBLEED=OFF
        -DWITH_WOLFSSL=OFF
    BUILD_COMMAND ${EXEC} ninja
    INSTALL_COMMAND ${EXEC} ninja install
    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)

force_rebuild_git(nghttp2)
cleanup(nghttp2 install)
